/root/mugen-ubuntu-riscv/libs/locallibs/common_lib.sh: line 86: rpm: command not found
/root/mugen-ubuntu-riscv/libs/locallibs/common_lib.sh: line 87: dnf: command not found
Thu Feb  9 19:19:29 2023 - INFO  - Start to prepare the test environment.
oe_test_reboot.sh: line 26: [1: command not found
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/apt_manage.py", line 12, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:33 2023 - INFO  - End to prepare the test environment.
Thu Feb  9 19:19:33 2023 - INFO  - Start to run test.
===========loop 0==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:34 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:19:34 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:35 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:38 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 1==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:39 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:19:40 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:40 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:44 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 2==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:45 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:19:45 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:46 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:49 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 3==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:50 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:19:50 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:51 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:54 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 4==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:55 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:19:55 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:19:56 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:19:59 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 5==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:00 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:01 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:02 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:05 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 6==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:05 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:06 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:07 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:10 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 7==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:11 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:11 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:12 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:15 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 8==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:16 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:16 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:17 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:20 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 9==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:21 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:22 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:22 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:25 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 10==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:26 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:27 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:27 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:31 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 11==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:31 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:32 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:33 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:36 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 12==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:37 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:37 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:38 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:41 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 13==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:42 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:42 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:43 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:46 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 14==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:47 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:47 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:48 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:51 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 15==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:52 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:53 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:53 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:20:56 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 16==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:57 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:20:58 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:20:59 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:02 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 17==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:03 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:03 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:04 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:08 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 18==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:08 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:09 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:10 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:13 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 19==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:14 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:14 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:15 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:18 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 20==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:19 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:20 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:20 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:23 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 21==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:25 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:25 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:26 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:29 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 22==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:30 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:30 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:31 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:34 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 23==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:35 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:36 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:36 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:39 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 24==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:40 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:41 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:41 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:44 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 25==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:45 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:46 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:47 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:50 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 26==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:50 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:51 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:52 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:21:55 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 27==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:56 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:21:56 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:21:57 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:00 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 28==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:01 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:01 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:02 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:05 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 29==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:06 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:06 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:07 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:10 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 30==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:11 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:11 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:12 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:15 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 31==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:16 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:17 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:17 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:21 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 32==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:21 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:22 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:23 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:26 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 33==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:26 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:27 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:28 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:31 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 34==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:32 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:32 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:33 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:36 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 35==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:37 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:37 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:38 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:41 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 36==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:42 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:42 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:43 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:46 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 37==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:47 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:47 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:48 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:51 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 38==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:52 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:53 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:53 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:22:56 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 39==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:57 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:22:58 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:22:58 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:02 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 40==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:02 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:03 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:04 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:07 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 41==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:07 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:08 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:09 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:12 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 42==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:12 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:13 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:14 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:17 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 43==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:18 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:18 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:19 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:22 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 44==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:23 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:23 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:24 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:27 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 45==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:28 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:28 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:29 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:32 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 46==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:33 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:34 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:35 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:38 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 47==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:38 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:39 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:40 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:43 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 48==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:43 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:44 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:45 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:48 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 49==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:49 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:49 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:50 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:53 2023 - ERROR - oe_test_reboot.sh line 49
===========loop 50==============
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:54 2023 - ERROR - Failed in remote CMD operation:1
Thu Feb  9 19:23:54 2023 - ERROR - oe_test_reboot.sh line 40
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Thu Feb  9 19:23:55 2023 - ERROR - Failed in remote CMD operation:1
ping: usage error: Destination address required
Traceback (most recent call last):
  File "/root/mugen-ubuntu-riscv/libs/locallibs/remote_reboot.py", line 30, in <module>
    import ssh_cmd
  File "/root/mugen-ubuntu-riscv/libs/locallibs/ssh_cmd.py", line 23, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
Thu Feb  9 19:23:58 2023 - ERROR - oe_test_reboot.sh line 49
Thu Feb  9 19:23:59 2023 - INFO  - End to run test.
Thu Feb  9 19:23:59 2023 - ERROR - failed to execute the case.
Thu Feb  9 19:24:00 2023 - INFO  - Start to restore the test environment.
Thu Feb  9 19:24:00 2023 - WARN  - no thing to do.
Thu Feb  9 19:24:01 2023 - INFO  - End to restore the test environment.
